Make StylusDetection Faster
JasonBarnabe/greasyfork pull request #1165
Opened 2023-07-30 03:48 UTC by cyfung1031

The `200ms` shall not be necessary since the `Promise` can be directly resolved by `onMessage`

2023-09-24 23:10 UTC, JasonBarnabe requested changes
Thanks for the suggestion. The general idea is good, but see the comments.

If you're not interested in adjusting the PR, let me know (or just don't say anything for a bit) and I'll do it myself, but not sure if you'll get credit in git history if I do it that way.

2023-09-24 23:10 UTC, JasonBarnabe commented on app/javascript/managers.js
> +  if (localStorage.getItem('stylusDetected') === '1') {
Don't make unrelated changes like this, just it makes it harder for me to figure out what's going on and makes the git history messy.

2023-09-24 23:10 UTC, JasonBarnabe commented on app/javascript/managers.js
> +window.addEventListener("message", function (event) {
Unrelated changes

2023-09-24 23:10 UTC, JasonBarnabe commented on app/javascript/managers.js
> +  if (event.data.type === "style-version") {
Unrelated changes

2023-09-24 23:10 UTC, JasonBarnabe commented on app/javascript/managers.js
> +    window.stylusDetectedResolve = resolve;
I think this can be scoped as a variable outside of any function rather than setting on window.

2023-09-24 23:10 UTC, JasonBarnabe commented on app/javascript/managers.js
> +  await new Promise(resolve => {
Took me a few tries to figure out what's going on here, which probably means there should be a comment.

2023-09-26 15:49 UTC, cyfung1031 commented on app/javascript/managers.js
> +window.addEventListener("message", function (event) {
Reverted to `function(event)`

2023-09-26 15:52 UTC, cyfung1031 commented
@JasonBarnabe  I have changed the code as per your request. The event listener is now scoped inside `canInstallUserCSS()` and to be removed after timeout or detection.

2023-10-03 02:12 UTC, merged

2023-10-03 03:25 UTC, JasonBarnabe commented
I deployed this and tried it out and it didn't work. Seems like the message listener never fired for the `style-version` response from Stylus. Not sure why. I backed it out.

2023-10-03 03:38 UTC, JasonBarnabe commented
I believe it may be because [Stylus will only respond once](https://github.com/openstyles/stylus/blob/16b6d0b6ec8c40e5071a9cb55ffdecedc7e4eb99/content/install-hook-greasyfork.js#L14) and there's another query happening in [managers.js](https://github.com/JasonBarnabe/greasyfork/blob/2205c13df3bdddad6816b2ce4ee743ba3a90ad8d/app/javascript/managers.js#L17).

The previous code added the message listener immediately whereas yours only does so when the button is pressed, but by that time, Stylus has already fired its one and only message.

2023-10-03 04:22 UTC, cyfung1031 commented
Noted. Let me check it again later :)